version: '2'
services:
    db:
        image: mariadb
        restart: always
        volumes:
          - ./data:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: usergroups
        ports:
          - "3306:3306"
    php:
        build: ./api
        volumes:
          - ./api:/var/www
          - ./logs/symfony:/var/www/symfony/app/logs
        depends_on:
          - db
    nginx:
        build: ./nginx
        ports:
          - "80:80"
        volumes_from:
          - php
        volumes:
          - ./logs/nginx/:/var/log/nginx
        depends_on:
          - php